version: "3"

services:
  portfolio-frontend:
    container_name: portfolio-frontend
    build:
      context: ../../src/frontend
      dockerfile: ./docker/Dockerfile
    image: portfolio-frontend
    ports:
      - "80:80"
      - "443:443"
    restart: always
  portfolio-backend:
    container_name: portfolio-backend
    build:
      context: ../../src/backend
      dockerfile: ./docker/Dockerfile
    image: portfolio-backend
    ports:
      - "8000:8000"
    restart: always
