version: "3"
services:
  portfolio-frontend:
    image: registry.digitalocean.com/${DOCKER_REGISTRY}/portfolio-frontend:latest
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
  portfolio-backend:
    image: registry.digitalocean.com/${DOCKER_REGISTRY}/portfolio-backend:latest
    ports:
      - 8000:8000
    restart: always
