version: "3.9"

services:
    frontend:
        container_name: portfolio-fe-dev
        build:
            context: ../../src/frontend
            dockerfile: ./tools/docker/dockerfile.dev
        image: portfolio-fe-dev
        ports:
            - "3000:3000"
        restart: always
        volumes:
            - type: bind
              source: ../../src/frontend/src
              target: /portfolio-fe-dev/src
