version: "3"

services:
    portfolio-frontend-proxy:
        container_name: portfolio-frontend-proxy
        build:
            context: ../../src/frontend
            dockerfile: ./tools/docker/dockerfile.build
        image: portfolio-frontend-proxy
        ports:
            - "80:80"
            - "443:443"
        restart: always
    portfolio-frontend:
        container_name: portfolio-frontend
        build:
            context: ../../src/frontend
            dockerfile: ./tools/docker/dockerfile.next
        image: portfolio-frontend
        ports:
            - "3000:3000"
        restart: always
    portfolio-backend:
        container_name: portfolio-backend
        build:
            context: ../../src/backend
            dockerfile: ./docker/Dockerfile
        image: portfolio-backend
        ports:
            - "8000:8000"
        restart: always
