name: Docker Image CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout all the submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker compose -f tools/docker/docker-compose.yml build
