name: Docker Image CI
on:
  push:
    branches:
      - "test/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout all the submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: run tests
        run: make tests
