name: Docker Image CI
on:
  push:
    branches:
      - "test/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout all the submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: upgrade python
        run: add-apt-repository ppa:deadsnakes/ppa -y && apt update -y && apt install python3.12 -y
      - name: install deps
        run: pip install poetry && poetry install && poetry shell
      - name: run tests
        run: make tests
