name: Docker Image CI
on:
  push:
    branches:
      - "test/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout all the submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: run fe tests
        run: cd src/frontend && npm run test
      - name: run be tests
        run: cd ../../ make tests
